// <auto-generated />
using System;
using Blog.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240317185146_SeedUserTable")]
    partial class SeedUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogBE.Models.Post", b =>
                {
                    b.Property<int>("Unique_Id_Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unique_Id_Post"));

                    b.Property<string>("author_user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("last_modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Unique_Id_Post");

                    b.ToTable("PostProperties");
                });

            modelBuilder.Entity("BlogBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_online")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            created_at = new DateTime(2024, 3, 17, 20, 51, 45, 997, DateTimeKind.Local).AddTicks(5026),
                            email = "raymond@yahoo.com",
                            is_Admin = true,
                            last_online = new DateTime(2024, 3, 17, 20, 51, 45, 997, DateTimeKind.Local).AddTicks(5061),
                            password = "12345",
                            profile_description = "lalala 1 2 3",
                            username = "mamaleone"
                        },
                        new
                        {
                            Id = 2,
                            created_at = new DateTime(2024, 3, 17, 20, 51, 45, 997, DateTimeKind.Local).AddTicks(5064),
                            email = "razvan@yahoo.com",
                            is_Admin = true,
                            last_online = new DateTime(2024, 3, 17, 20, 51, 45, 997, DateTimeKind.Local).AddTicks(5065),
                            password = "1223",
                            profile_description = "razvan 1 2 3",
                            username = "razvan"
                        },
                        new
                        {
                            Id = 3,
                            created_at = new DateTime(2024, 3, 17, 20, 51, 45, 997, DateTimeKind.Local).AddTicks(5067),
                            email = "adrian@yahoo.com",
                            is_Admin = false,
                            last_online = new DateTime(2024, 3, 17, 20, 51, 45, 997, DateTimeKind.Local).AddTicks(5068),
                            password = "123456",
                            profile_description = "adrian 1 2 3",
                            username = "adrian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
