// <auto-generated />
using System;
using Blog.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240321235351_PossibleFixWithDatabaseConfiguration")]
    partial class PossibleFixWithDatabaseConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Models.Post", b =>
                {
                    b.Property<int>("Unique_Id_Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unique_Id_Post"));

                    b.Property<string>("author_user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("post_replies")
                        .HasColumnType("int");

                    b.HasKey("Unique_Id_Post");

                    b.HasIndex("author_user_id");

                    b.ToTable("PostProperties");

                    b.HasData(
                        new
                        {
                            Unique_Id_Post = 1,
                            author_user_id = "7e245a45-352d-4486-98c4-035eecf15875",
                            content = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "REACT FRONT?",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4360)
                        },
                        new
                        {
                            Unique_Id_Post = 2,
                            author_user_id = "a2eb4331-a44e-4652-aeee-140ce222f37e",
                            content = "n looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "WORLD OF WARCRAFT BEST MMO",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4364)
                        },
                        new
                        {
                            Unique_Id_Post = 3,
                            author_user_id = "bad532d4-d537-415b-bc4d-b4718a3dd162",
                            content = "Itoking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "SOMETHING",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4366)
                        },
                        new
                        {
                            Unique_Id_Post = 4,
                            author_user_id = "e5a74233-81d1-4874-8fe7-a87e5fedb3d0",
                            content = "Iis a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "WHY WHY WHY?",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4401)
                        },
                        new
                        {
                            Unique_Id_Post = 5,
                            author_user_id = "e5a74233-81d1-4874-8fe7-a87e5fedb3d0",
                            content = "It is a long established fact that a reader will be distr ",
                            content_title = ".NET BLOG ?",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4404)
                        },
                        new
                        {
                            Unique_Id_Post = 6,
                            author_user_id = "62b303f6-6e23-4dd6-915b-8ec1559ebb48",
                            content = "It is a long es ",
                            content_title = "With whom should we use it?",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4406)
                        },
                        new
                        {
                            Unique_Id_Post = 7,
                            author_user_id = "a8adb7ad-d3c6-446b-898b-d26ccc26987d",
                            content = "Lalala",
                            content_title = "What is Lorem Impsum ?",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4408)
                        },
                        new
                        {
                            Unique_Id_Post = 8,
                            author_user_id = "e37b1d7b-6928-4b4d-ae69-aa7cab3fd10f",
                            content = "Ce sa faci atunci cand te doare capul ?  ",
                            content_title = "Doare capul ?",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4410)
                        });
                });

            modelBuilder.Entity("Blog.Models.PostReply", b =>
                {
                    b.Property<int>("PostReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostReplyId"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("fatherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("likes")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostReplyId");

                    b.HasIndex("PostId");

                    b.ToTable("PostReplyProperties");

                    b.HasData(
                        new
                        {
                            PostReplyId = 1,
                            PostId = 4,
                            content = " !!!!!!! CE TAREE EEEE!",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4440),
                            fatherId = 0,
                            last_modified = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4442),
                            likes = 0,
                            username = "adrian"
                        },
                        new
                        {
                            PostReplyId = 2,
                            PostId = 2,
                            content = " haha, ce tare !",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4445),
                            fatherId = 0,
                            last_modified = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4446),
                            likes = 0,
                            username = "adrian"
                        },
                        new
                        {
                            PostReplyId = 3,
                            PostId = 3,
                            content = " wow, incredibil",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4448),
                            fatherId = 0,
                            last_modified = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4449),
                            likes = 1,
                            username = "razvan"
                        },
                        new
                        {
                            PostReplyId = 4,
                            PostId = 4,
                            content = " haha, senzational!",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4451),
                            fatherId = 0,
                            last_modified = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4453),
                            likes = 1,
                            username = "raymond"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_online")
                        .HasColumnType("datetime2");

                    b.Property<string>("profile_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "b6f83aaf-6c57-44ff-abff-9a365f039f0d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16a7ee21-d701-4e67-9b57-b592d421a1f2",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7ebbcde5-9b6d-48d3-8c0c-de4833085b49",
                            TwoFactorEnabled = false,
                            Name = "Adrian",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4169),
                            profile_description = "lalala 1 2 3"
                        },
                        new
                        {
                            Id = "5867d2de-394f-42b1-9036-d388a7be86d8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d48785f8-4598-4675-a84e-5606766d2905",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad4a463c-beb5-4f21-b3fe-ed341a77e8e0",
                            TwoFactorEnabled = false,
                            Name = "jijel",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4227),
                            profile_description = "razvan 1 2 3"
                        },
                        new
                        {
                            Id = "f83af9de-0fb0-48e1-ae16-b1d99bf27a76",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "182647d4-718e-4331-8abb-1d86987efa7a",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1abffcab-e005-4a8c-bff9-1141ca1a2139",
                            TwoFactorEnabled = false,
                            Name = "ciaciu",
                            created_at = new DateTime(2024, 3, 22, 1, 53, 50, 343, DateTimeKind.Local).AddTicks(4232),
                            profile_description = "adrian 1 2 3"
                        });
                });

            modelBuilder.Entity("Blog.Models.Post", b =>
                {
                    b.HasOne("Blog.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("author_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Models.PostReply", b =>
                {
                    b.HasOne("Blog.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
