// <auto-generated />
using System;
using Blog.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240318082722_SeedPostsTable")]
    partial class SeedPostsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogBE.Models.Post", b =>
                {
                    b.Property<int>("Unique_Id_Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unique_Id_Post"));

                    b.Property<string>("author_user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("last_modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Unique_Id_Post");

                    b.ToTable("PostProperties");

                    b.HasData(
                        new
                        {
                            Unique_Id_Post = 1,
                            author_user_id = "mamaleone",
                            content = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "REACT FRONT?",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1625),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1627)
                        },
                        new
                        {
                            Unique_Id_Post = 2,
                            author_user_id = "mamaleone",
                            content = "n looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "WORLD OF WARCRAFT BEST MMO",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1629),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1630)
                        },
                        new
                        {
                            Unique_Id_Post = 3,
                            author_user_id = "mamaleone",
                            content = "Itoking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "SOMETHING",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1632),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1633)
                        },
                        new
                        {
                            Unique_Id_Post = 4,
                            author_user_id = "razvan",
                            content = "Iis a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "WHY WHY WHY?",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1635),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1636)
                        },
                        new
                        {
                            Unique_Id_Post = 5,
                            author_user_id = "mamaleone",
                            content = "It is a long established fact that a reader will be distr ",
                            content_title = ".NET BLOG ?",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1638),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1639)
                        },
                        new
                        {
                            Unique_Id_Post = 6,
                            author_user_id = "adrian",
                            content = "It is a long es ",
                            content_title = "With whom should we use it?",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1641),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1642)
                        },
                        new
                        {
                            Unique_Id_Post = 7,
                            author_user_id = "adrian",
                            content = "Lalala",
                            content_title = "What is Lorem Impsum ?",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1643),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1645)
                        },
                        new
                        {
                            Unique_Id_Post = 8,
                            author_user_id = "razvan",
                            content = "Ce sa faci atunci cand te doare capul ?  ",
                            content_title = "Doare capul ?",
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1646),
                            last_modified = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1647)
                        });
                });

            modelBuilder.Entity("BlogBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_online")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1475),
                            email = "raymond@yahoo.com",
                            is_Admin = true,
                            last_online = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1513),
                            password = "12345",
                            profile_description = "lalala 1 2 3",
                            username = "mamaleone"
                        },
                        new
                        {
                            Id = 2,
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1516),
                            email = "razvan@yahoo.com",
                            is_Admin = true,
                            last_online = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1517),
                            password = "1223",
                            profile_description = "razvan 1 2 3",
                            username = "razvan"
                        },
                        new
                        {
                            Id = 3,
                            created_at = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1519),
                            email = "adrian@yahoo.com",
                            is_Admin = false,
                            last_online = new DateTime(2024, 3, 18, 10, 27, 22, 109, DateTimeKind.Local).AddTicks(1520),
                            password = "123456",
                            profile_description = "adrian 1 2 3",
                            username = "adrian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
