// <auto-generated />
using System;
using Blog.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240318204129_FatherIdToPostReplyModelAndSeed")]
    partial class FatherIdToPostReplyModelAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogBE.Models.Post", b =>
                {
                    b.Property<int>("Unique_Id_Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unique_Id_Post"));

                    b.Property<string>("author_user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("last_modified")
                        .HasColumnType("datetime2");

                    b.HasKey("Unique_Id_Post");

                    b.ToTable("PostProperties");

                    b.HasData(
                        new
                        {
                            Unique_Id_Post = 1,
                            author_user_id = "mamaleone",
                            content = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "REACT FRONT?",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4835),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4838)
                        },
                        new
                        {
                            Unique_Id_Post = 2,
                            author_user_id = "mamaleone",
                            content = "n looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "WORLD OF WARCRAFT BEST MMO",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4840),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4841)
                        },
                        new
                        {
                            Unique_Id_Post = 3,
                            author_user_id = "mamaleone",
                            content = "Itoking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "SOMETHING",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4843),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4844)
                        },
                        new
                        {
                            Unique_Id_Post = 4,
                            author_user_id = "razvan",
                            content = "Iis a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. ",
                            content_title = "WHY WHY WHY?",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4846),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4847)
                        },
                        new
                        {
                            Unique_Id_Post = 5,
                            author_user_id = "mamaleone",
                            content = "It is a long established fact that a reader will be distr ",
                            content_title = ".NET BLOG ?",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4849),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4850)
                        },
                        new
                        {
                            Unique_Id_Post = 6,
                            author_user_id = "adrian",
                            content = "It is a long es ",
                            content_title = "With whom should we use it?",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4852),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4853)
                        },
                        new
                        {
                            Unique_Id_Post = 7,
                            author_user_id = "adrian",
                            content = "Lalala",
                            content_title = "What is Lorem Impsum ?",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4855),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4856)
                        },
                        new
                        {
                            Unique_Id_Post = 8,
                            author_user_id = "razvan",
                            content = "Ce sa faci atunci cand te doare capul ?  ",
                            content_title = "Doare capul ?",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4858),
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4859)
                        });
                });

            modelBuilder.Entity("BlogBE.Models.PostReply", b =>
                {
                    b.Property<int>("PostReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostReplyId"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("fatherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("likes")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostReplyId");

                    b.ToTable("PostReplyProperties");

                    b.HasData(
                        new
                        {
                            PostReplyId = 1,
                            content = " !!!!!!! CE TAREE EEEE!",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4879),
                            fatherId = 4,
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4881),
                            likes = 0,
                            username = "adrian"
                        },
                        new
                        {
                            PostReplyId = 2,
                            content = " haha, ce tare !",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4883),
                            fatherId = 4,
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4885),
                            likes = 0,
                            username = "adrian"
                        },
                        new
                        {
                            PostReplyId = 3,
                            content = " wow, incredibil",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4887),
                            fatherId = 4,
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4888),
                            likes = 1,
                            username = "razvan"
                        },
                        new
                        {
                            PostReplyId = 4,
                            content = " haha, senzational!",
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4890),
                            fatherId = 4,
                            last_modified = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4891),
                            likes = 1,
                            username = "raymond"
                        });
                });

            modelBuilder.Entity("BlogBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_online")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4639),
                            email = "raymond@yahoo.com",
                            is_Admin = true,
                            last_online = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4681),
                            password = "12345",
                            profile_description = "lalala 1 2 3",
                            username = "mamaleone"
                        },
                        new
                        {
                            Id = 2,
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4684),
                            email = "razvan@yahoo.com",
                            is_Admin = true,
                            last_online = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4685),
                            password = "1223",
                            profile_description = "razvan 1 2 3",
                            username = "razvan"
                        },
                        new
                        {
                            Id = 3,
                            created_at = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4729),
                            email = "adrian@yahoo.com",
                            is_Admin = false,
                            last_online = new DateTime(2024, 3, 18, 22, 41, 29, 206, DateTimeKind.Local).AddTicks(4731),
                            password = "123456",
                            profile_description = "adrian 1 2 3",
                            username = "adrian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
